import { Inter } from 'next/font/google'
import './globals.css';
import styles from './layout.module.css'
import LeftMenu from "@/components/LeftMenu";
import RightMenu from "@/components/RigthMenu";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Go Meal',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className={styles.main}>
        <LeftMenu/>
        <div className={styles.content}>
        {children}
        </div>
        <RightMenu/>
      </div>
      </body>
    </html>
  )
}
